#' Set up potions for easy data retrieval
#' 
#' Start-up function to place a list into `options` with a specified 
#' slot name.
#' @param .data a list containing data to be stored via `options()`.
#' @param .slot string: optional name to mandate where data is stored. Defaults 
#' to a random string generated by `stringi::stri_rand_strings`.
#' @param .pkg string: package name that `potions` is being used within. If 
#' using {potions} within a package development process, set this argument 
#' instead of `slot`.
#' @importFrom rlang abort
#' @details 
#' The default method is to use `brew` and set either `.pkg` or `.slot`, but not
#' both. Alternatively you can use `brew_package()` or `brew_interactive()`. 
#' Note that if neither `.slot` or `.pkg` are set, `potions` defaults to `.slot`
#' , unless `.pkg` information has previously been supplied (and `.slot` 
#' information has not). This might be undesirable in a package development 
#' situation.
#' 
#' If no `.data` argument is given, this function sets up an empty `potions` 
#' object in `options("potions-pkg")`. See `potions-class` for more information.
#' 
#' If the user repeatedly calls `brew()`, later list entries overwrite early 
#' entries. Whole lists are not overwritten unless all top-level entry names 
#' match.
#' @export
brew <- function(.data, .slot, .pkg){
  
  # determine behavior based on supplied arguments
  has_slot <- !missing(.slot)
  has_pkg <- !missing(.pkg)
  if(has_slot){
    if(has_pkg){
      abort("Both `.slot` and `.pkg` have been set; please choose one")
    }
    brew_interactive(.data, .slot)
  }else{
    if(has_pkg){
      brew_package(.data, .pkg)
    }else{ # if .slot and .pkg missing, choose based on call location
      package_check <- trace_back()$namespace |> 
        check_within_pkg()
      if(package_check$within){
        brew_package(.data, .pkg = package_check$pkg)
      }else{
        lookup <- check_existing_slots()
        switch(lookup$method,
               "all_empty" = {brew_interactive(.data)}, # no data; .slot is random
               # ".pkg" = {brew_package(.data, .pkg = lookup$value)}, # impossible
               ".slot" = {brew_interactive(.data, .slot = lookup$value)}) 
      }
    }
  }
}

#' @rdname brew
#' @export
brew_package <- function(.data, .pkg){
  check_is_character(.pkg)
  check_length_one(.pkg)
  current_list <- check_potions_storage() |>
    update_package_names(.pkg) |>
    update_package_data(provided = .data, pkg = .pkg)
  options(list("potions-pkg" = current_list))
}

#' @rdname brew
#' @export
brew_interactive <- function(.data, .slot){
  .slot <- enforce_slot_name(.slot) # generates a random slot if not given
  check_is_character(.slot) # for case where .slot is given, but is not a character
  check_length_one(.slot)
  current_list <- check_potions_storage() |> 
                  update_default_name(.slot = .slot) |>
                  update_slot_data(.data, .slot)
  options(list("potions-pkg" = current_list))
}